### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ByKyTa** [KoreanDude/csgo-ze-plugins#1]
ShowDMG.phrases in folder ZR Show Damage

**Comment by KoreanDude** [comment]
updated

**Comment by KoreanDude** [comment]
updated

**Comment by KoreanDude** [comment]
updated

**Comment by ByKyTa** [comment]
File LOG 
L 06/04/2019 - 22:34:15: [SM] Exception reported: Expected 4th parameter, found none
L 06/04/2019 - 22:34:15: [SM] Blaming: test\uncacheparticle.smx
L 06/04/2019 - 22:34:15: [SM] Call stack trace:
L 06/04/2019 - 22:34:15: [SM]   [0] SDKCall
L 06/04/2019 - 22:34:15: [SM]   [1] Line 176, uncacheparticle.sp::ParticlesFindTable
L 06/04/2019 - 22:34:15: [SM]   [2] Line 125, uncacheparticle.sp::ParticlesOnCacheData
L 06/04/2019 - 22:34:15: [SM]   [3] Line 93, uncacheparticle.sp::OnMapStart
