### ISSUE TITLE
Entwatch HUD Default pos?

### ISSUE THREAD

**Issue by zeddy1234** [KoreanDude/csgo-ze-plugins#3]
Hi, can you also add a cvar for default HUD for all player? Its on the extreme left, it blocks MSAY message and Map vote.

**Comment by KoreanDude** [comment]
i will add cvar

**Comment by KoreanDude** [comment]
updated, i'm not tested it

**Comment by zeddy1234** [comment]
Don't work. It still show on left even after I change default pos.

**Comment by KoreanDude** [comment]
updated, please tell me if it works.
If you have any questions, please add a friend tentenserver (my steamid), because i confirm Github late.
