### ISSUE TITLE
Hello We Need Countdown for maps

### ISSUE THREAD

**Issue by Meguzio** [KoreanDude/csgo-ze-plugins#9]
COUNTDOWN FOR MAPS LIKE : ze_aot_trost_v6  ,ze_pirates_port_royal_v5_6  
FOR EXAMPLE: >>> GATES WILL BE OPEN ON 20 SEONCDS<<< 
CONFIGS /materials are missing for this 2 maps and ofc COUNTDOWN is missing Zombie Escape Mod

**Comment by Meguzio** [comment]
Here is photo
![Uploading 20220517_224800.jpg…]()

**Comment by KoreanDude** [comment]
https://github.com/Stewart-Anubis/Chat-Hud-Countdown-Translator-Anubis-Edition
